### PR TITLE
Fixing support for Cygwin

### PR DESCRIPTION
**Pull request by Lucas-C**
Should solve #178

### CODE REVIEW

**Comment by ekalinin** [comment]
Thanks!

**Comment by Lucas-C** [comment]
I didn't see the Travis CI check.
It seemes that I broke the line characters limit:
- https://github.com/Lucas-C/nodeenv/blob/master/nodeenv.py#L759
- https://github.com/Lucas-C/nodeenv/blob/master/nodeenv.py#L839

Do you want me to send a PR with a fixed version ?

**Comment by ekalinin** [comment]
I've fixed it already ;)
  * 96bcdb6f42e3298c5fde19585175c58565c30d2a
  * cd59d83f677057ad3cf2aba427ce8c0df83f8d04

**Comment by Lucas-C** [comment]
Thanks a lot :)

Also, when do you plan to release the next version please ?

**Comment by ekalinin** [comment]
> Also, when do you plan to release the next version please ?

@Lucas-C think I'll do it this week

**Comment by Lucas-C** [comment]
Thanks !

**Comment by ekalinin** [comment]
@Lucas-C https://github.com/ekalinin/nodeenv/releases/tag/1.2.0

**Comment by Lucas-C** [comment]
Cheers :)

**Pull request merged**
